import { defineConfig } from "tsdown";

// ESM-only library build. Declarations are generated by oxc via the tsconfig's
// `isolatedDeclarations`, so the build is independent of the TypeScript version.
export default defineConfig({
	entry: ["./src/index.ts"],
	format: "esm",
	dts: true,
	clean: true,
	sourcemap: false,
	// Strip comments/JSDoc from the shipped bundle (kept in source) to stay tiny,
	// without mangling or compressing (readable dist).
	minify: { compress: false, mangle: false },
});
